apiVersion: v1
kind: Service
metadata:
  name: team1
spec:
  type: NodePort
  ports:
  - name: web
    nodePort: 30910
    port: 9090
    protocol: TCP
    targetPort: web
  selector:
    prometheus: team1